services:
  # A Docker web service
  - type: web
    name: dq_the_file_donor
    env: docker
    repo: https://github.com/Joelkb/DQ-the-file-donor.git # optional
    region: oregon # optional (defaults to oregon)
    plan: starter # optional (defaults to starter)
    branch: Link-shortner # optional (defaults to master)
    rootDir: dq_the_file_donor
    dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
